spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: liquibase/changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8081